### ISSUE TITLE
Error Connecting Account?

### ISSUE THREAD

**Issue by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [IngoS11/ha-schluter#15]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/schluter/__init__.py", line 47, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I get a success message upon submitting my login credentials. But it says Failed to Setup in the integration and the logs how this message. I can confirm I am able to login and access my thermostat from the website.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
b834e0e9f020a624db6e4c0d0cd41403a5a19991 solved this issue for me.
